name: Build PassWall Xray OpenWrt 25.12 x86_64

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:

    - name: Checkout small
      uses: actions/checkout@v4


    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          build-essential \
          rsync \
          zstd \
          python3


    - name: Download OpenWrt SDK
      run: |

        wget -q https://downloads.openwrt.org/releases/25.12.0/targets/x86/64/openwrt-sdk-25.12.0-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst

        tar --use-compress-program=unzstd \
          -xf openwrt-sdk-25.12.0-x86-64_gcc-14.3.0_musl.Linux-x86_64.tar.zst

        mv openwrt-sdk-* sdk


    - name: Prepare SDK feeds
      run: |

        cd sdk

        cat > feeds.conf.default <<EOF
src-git packages https://github.com/openwrt/packages.git
src-git luci https://github.com/openwrt/luci.git
src-git routing https://github.com/openwrt/routing.git
EOF


    - name: Update base feeds
      run: |

        cd sdk

        ./scripts/feeds update -a

        ./scripts/feeds install -a


    - name: Add small feed
      run: |

        cd sdk

        mkdir -p feeds/small

        rsync -a \
        --exclude='.git' \
        "$GITHUB_WORKSPACE/" \
        feeds/small/


    - name: Install PassWall package
      run: |

        cd sdk

        ./scripts/feeds install -p small -f luci-app-passwall


    - name: Configure
      run: |

        cd sdk

        make defconfig


    - name: Compile
      run: |

        cd sdk

        make package/feeds/small/luci-app-passwall/compile V=s


    - name: Collect packages
      run: |

        mkdir output

        find sdk/bin/packages \
        -name "*.ipk" \
        -exec cp {} output/ \;


    - name: Upload
      uses: actions/upload-artifact@v4

      with:

        name: PassWall-Xray-OpenWrt25.12-x86_64

        path: output/
